{% set name = "napari-roi-registration" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-roi-registration-{{ version }}.tar.gz
  sha256: d305ca5b208f81c8e777f103c9334894ca937f274709eb33c7f9240e818afd8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - openpyxl  # Not imported but in requirements
    - pandas  # Imported but not in requirements
    - python >={{ python_min }}
    - qtpy  # Not imported but in requirements
    - scikit-image

test:
  imports:
    - napari_roi_registration
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-roi-registration
  summary: A plugin to perform roi registration.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/GiorgiaTortora/napari-roi-registration

extra:
  recipe-maintainers:
    - GiorgiaTortora
    - goanpeca
    - jaimergp
